### ISSUE TITLE
invalid-token-request

### ISSUE THREAD

**Issue by challo2018** [ldb2000/Viessman-API#1]
Hello, i found your code trough french thread on jeedom. i have an vitoconnect with vitocal 200a and connected vitovent 300w. i'm trying to connect this to my loxone smarthome. I'll like to help you and others working on this api. I tried your script with my username and passwort. but getting following error. Any idea why?

GetCODEcode= Error: {"error":"invalid-token-request"}access token= ok array(1) { [0]=> string(22) "Authorization: Bearer " } resource: 200 Installation= Gateway= ok array(1) { [0]=> string(22) "Authorization: Bearer " } resource: 200

$response from "GetCode" ist following:

ERROR!: error class 'Client Error'; error code '400'; error text 'bad request'

Thanks for your work and best regards!

**Comment by ldb2000** [comment]
Hi challo2018,

Have you turned on the debug in the script ? 
If you don't have any code returned, I think that it is an authorization issue. $isiwebuserid/$isiwebpasswd 

Are you able to run able some shell command ?

```
export CLIENTID=8ad97aceb92c5892e102b093c7c083fa
export CLIENTSECRET=8ad97aceb92c5892e102b093c7c083fa
export TOKEN_EP=https://iam.viessmann.com/idp/v1/token
export AUTHZ_EP=https://iam.viessmann.com/idp/v1/authorize
export SCOPE=openid
export REDIRECTURI=vicare://oauth-callback/everest
echo "$AUTHZ_EP?client_id=$CLIENTID&scope=$SCOPE&redirect_uri=$REDIRECTURI&response_type=code"
```

the echo command should give you an url, copy/paste it to a web browser.  It should prompt you the login/password. What is the result of this page ? 

thanks

**Comment by ldb2000** [comment]
Are you using the same password as the vicare app ?

**Comment by challo2018** [comment]
thanks for quick response. i'm running php script on webserver without shell access. login credentials are same as vicare app... I'll try to run your shell commands on raspberry pi. this should work, right?

**Comment by challo2018** [comment]
I'm getting this url: https://iam.viessmann.com/idp/v1/authorize?client_id=8ad97aceb92c5892e102b093c7c083fa&scope=openid&redirect_uri=vicare://oauth-callback/everest&response_type=code

Response is: {"error":"Client not registered."}


Opening "old" API URL: https://api.viessmann.io/estrella/rest/v2.0/gateways/
is working with same login credentials as used in your script

**Comment by ldb2000** [comment]
Sorry, I have sent you something wrong, use this line:
`export CLIENTID=79742319e39245de5f91d15ff4cac2a8`

So the URL should be:
`https://iam.viessmann.com/idp/v1/authorize?client_id= 79742319e39245de5f91d15ff4cac2a8&scope=openid&redirect_uri=vicare://oauth-callback/everest&response_type=code`

In the URL returned, you have the code.
To continue and valide the process:
```
export CODE=code_found
curl -k --user "$CLIENTID:$CLIENTSECRET" -d "code=$CODE&grant_type=authorization_code&client_id=$CLIENTID&redirect_uri=$REDIRECTURI" $TOKEN_EP
```

the token should be given by the following son
```
{
    "access_token": "TOKEN_TO_BE_TAKEN",
    "id_token": "....",
    "token_type": "Bearer",
    "expires_in": 3600
}
```

Run the following command and voila :)
```
export CODE=TOKEN_TO_BE_TAKEN
curl -k  -H "AUTHORIZATION: Bearer $TOKEN" "https://api.viessmann-platform.io/general-management/installations?expanded=true&"  

```

**Comment by ldb2000** [comment]
On your web server, you need to have some php libraries, I think.
Something like 
`apt-get install php5-curl `

**Comment by ldb2000** [comment]
For your information I will add some testing to have more logs, but it will be tomorrow

**Comment by challo2018** [comment]
when i execute your steps with new clientid on raspberry pi console -> i'm getting url for brwoser and can see the login form. but when i press "login" in chrome browser nothing new appears. how can i see the "code"?

**Comment by ldb2000** [comment]
In the url of chrome, it should have change vicare://oauth-callback/everest?code=XXXXXXX

**Comment by challo2018** [comment]
thats strange... url is not changing when i press "login" i also tried internet explorer. IE wants to open an app from appstore. but also URL stays the same. no code is shown.
![2018-08-27_22h07_19](https://user-images.githubusercontent.com/42739411/44683139-aefbc100-aa45-11e8-8b88-f185bbd28581.png)

**Comment by challo2018** [comment]
I tried with "Postman" then it's working and i'm getting the token id!

**Comment by ldb2000** [comment]
Good. Are you using a proxy like Squid ? It is very strange that chrome don't do the redirection... For IE, it is normal that it try to go on the app store as the url return is something like vicare:// and not http://

**Comment by ldb2000** [comment]
I have upload a bash script that should work (retrieving automatically the CODE, the TOKEN and do a API request...

**Comment by challo2018** [comment]
thanks i'll try. how can i find out the name of the request?  Example in your php script is: features/heating.sensors.temperature.outside

-> Its working with your bash script. i', getting quite longe response. now i need to find out how to read values and names of the values

**Comment by challo2018** [comment]
Now i got it! I can send request for all features with /features?  Thanks a lot for your help!!!

**Comment by ldb2000** [comment]
Perfect. I will close the issue, but don't hesitate to open a new one for any help/support.
